import Head from 'next/head';
import dynamic from 'next/dynamic';
import 'smart-webcomponents-react/source/styles/smart.default.css';
import styles from '../styles/Home.module.css';
import GetData from '../public/data'; //NextJS cannot load named modules

//Dynamically import the Smart.Grid component
const Grid = dynamic(() => import('smart-webcomponents-react/grid'), {
    ssr: false, //no server-side rendering
    loading: () => <p>Loading...</p>
});

function Home() {
    const columns = [{
            label: 'First Name',
            dataField: 'firstName'
        },
            {
                label: 'Last Name',
                dataField: 'lastName'
            },
            {
                label: 'Product',
                dataField: 'productName'
            },
            {
                label: 'Quantity',
                dataField: 'quantity',
                align: 'right',
                cellsAlign: 'right',
            },
            {
                label: 'Unit Price',
                dataField: 'price',
                align: 'right',
                cellsAlign: 'right',
                cellsFormat: 'c2'
            },
            {
                label: 'Total',
                dataField: 'total',
                align: 'right',
                cellsAlign: 'right',
                cellsFormat: 'c2'
            }],
        selection = {
            enabled: true,
            checkBoxes: {
                enabled: true
            }
        },
        dataSource = GetData(300),
        dataSourceSettings = {
            dataFields: [
                { name: 'id', dataType: 'number' },
                { name: 'firstName', dataType: 'string' },
                { name: 'lastName', dataType: 'string' },
                { name: 'productName', dataType: 'string' },
                { name: 'quantity', dataType: 'number' },
                { name: 'price', dataType: 'number' },
                { name: 'total', dataType: 'number' }
            ]
        };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to Next.js!
                </h1>

                <Grid className={styles.smartGrid} id="grid" columns={columns} selection={selection} dataSource={dataSource} dataSourceSettings={dataSourceSettings}></Grid>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://www.htmlelements.com/react/demos/grid/grid-chart-dynamic-data/"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <img src="https://www.htmlelements.com/wp-content/design/assets/images/logo-htmlelements.svg" className={styles.imgLogo} />
                </a>
            </footer>
        </div>
    );
}

export default Home;